language: node_js
node_js:
    - "0.10"

env:
    - USE_ORACLE_DUMMY=1

script:
    - "npm run lint"
    - "npm run test"

install:
    - npm install jshint --global
    - jshint --version
    - npm install jsonlint --global
    - jsonlint --version
    - npm install

notifications:
  email:
    - doberkofler.github@gmail.com
