language: node_js

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

#os:
#  - linux
#  - osx

node_js:
  - "4.0"
  - "4.1"
  - "4.2"
  - "5"
  - "iojs"

env:
  global:
    - CXX=g++-4.8
    - USE_ORACLE_DUMMY=1

before_script:
  - npm install -g gulp

script:
  - "gulp lint"
  - "gulp test"

install:
  - npm install

notifications:
  email:
    - dieter.oberkofler@gmail.com
