language: node_js

node_js:
  - "0.10"
  - "0.11"
  - "0.12"
  - "iojs"

env:
  - USE_ORACLE_DUMMY=1

before_script:
  - npm install -g gulp

script:
  - "gulp lint"
  - "gulp test"
  - "gulp coveralls"

install:
  - npm install

notifications:
  email:
    - doberkofler.github@gmail.com
