language: node_js

#os:
#  - linux
#  - osx

node_js:
  - "4.0"
  - "4.1"
  - "4.2"
  - "iojs"

env:
  - USE_ORACLE_DUMMY=1

before_script:
  - npm install -g gulp

script:
  - "gulp lint"
  - "gulp test"

install:
  - npm install

notifications:
  email:
    - dieter.oberkofler@gmail.com
