language: node_js

node_js:
  - "0.10"
  - "0.11"

matrix:
  allow_failures:
    - node_js: "0.11"

env:
  - USE_ORACLE_DUMMY=1

before_script:
  - npm install -g grunt-cli

script:
  - "grunt lint"
  - "grunt test"

install:
  - npm install

notifications:
  email:
    - doberkofler.github@gmail.com
